--------------- General Configuration Files ---------------

require("config/plugins")
require("config/setup")
require("config/mappings")
require("config/commands")

--------------- Self Tool Building ---------------

require("tools/themes")
require("tools/windows")
require("tools/startup")
require("tools/buffers")
require("tools/highlights")
--require("tools/shade")
--require("tools/holdin")
--require('tools/icons')
--require('tools/terminal')
--require('tools/statusline')
--require('tools/bufferline')
--require('tools/tabline')

--------------- Plugins Configuration Files ---------------

require("plugins/fold")
--require('plugins/move')
require("plugins/icons")
require("plugins/signs")
require("plugins/pairs")
require("plugins/shift")
require("plugins/wilder")
require("plugins/indent")
require("plugins/parser")
require("plugins/finder")
require("plugins/scroll")
require("plugins/search")
--require("plugins/column")
require("plugins/winbar")
require("plugins/comment")
--require("plugins/symbols")
require("plugins/terminal")
require("plugins/whichkey")
require("plugins/document")
require("plugins/snippets")
require("plugins/animation")
require("plugins/completion")
require("plugins/languages")
require("plugins/explorer")
require("plugins/statusline")
require("plugins/bufferline")
